contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #vcffilter channel"
    url: https://nfcore.slack.com/channels/vcffilter
    about: Discussion about the nf-core/vcffilter pipeline
